ln -s ~/dotfiles/.aspell.en.pws ~/.aspell.en.pws
ln -s ~/dotfiles/.bash_profile ~/.bash_profile
ln -s ~/dotfiles/.emacs.d/init.el ~/.emacs.d/init.el
ln -s ~/dotfiles/.pandoc/dirty-shade.png ~/.pandoc/dirty-shade.png
ln -s ~/dotfiles/.pandoc/dirty-shade.png ~/.pandoc/dynoload.js
ln -s ~/dotfiles/.pandoc/dirty-shade.png ~/.pandoc/github.css
ln -s ~/dotfiles/.pandoc/dirty-shade.png ~/.pandoc/para.png
ln -s ~/.w3m/config ~/.w3m/config
ln -s ~/dotfiles/.zshrc ~/.zshrc
